- assets/css/_primitives-tokens.css
- assets/css/design-system.css
- assets/tokens/primitives.value.tokens.json
- assets/tokens/tokens.json
- assets/tokens/tokens.mode-1.tokens.json
- package-lock.json
- package.json
- scripts/generate-token-files.ts
- src/design-system/color/color-group.ts
- src/design-system/color/color-swatch.ts
- src/design-system/color/color.mdx
- src/design-system/color/color.stories.ts
- src/design-system/color/index.ts
- src/design-system/design-system.md
- style-dictionary.config.json
- tsconfig.json
Closes https://github.com/praxis-isncsci/ui/issues/9
**Figma** variables are our _source of truth_. They are exported into a `json` file using the plugin **Variables import export**. We need an automated way to import the tokens generated into our project.
This PR adds the package `style-dictionary` to our dev dependencies so we can convert the file generated from **Figma** into _CSS_ files by running `npm run update-design-tokens`. The script `scripts/generate-token-files.ts` has the code that performs the convertion.
The documentation on how the color palettes are generated, as well as the colors themselves, is in the **Storybook** story `Designsystem/color/docs`.
<details>
<summary>Use case</summary>
1. `npm run storybook`
2. In *Storybook*, navigate to …
> Color tokens

- assets/index.html
- src/app/app.ts
- src/app/controllers/inputLayout.controller.ts
- src/app/providers/appStore.provider.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.stories.ts
- src/app/store/appStore.ts
- src/app/store/reducers.ts
- src/core/boundaries/iAppState.ts
- src/core/boundaries/iIsncsciAppStore.provider.ts
- src/core/domain/index.ts
- src/core/domain/totals.ts
- src/core/helpers/examData.helper.spec.ts
- src/core/helpers/examData.helper.ts
- src/core/helpers/index.ts
- src/core/useCases/loadExternalExamData.useCase.ts
- src/index.ts
- src/web/praxisIsncsciTotals/praxisIsncsciTotals.stories.ts
- src/web/praxisIsncsciTotals/praxisIsncsciTotals.ts
Closes #32 
When totals are available, the app needs to update the application state and interfaces.
When data is pushed through the `ExternalMessageProtProvider`:
1. Add a step to the `loadExternalExamDataUseCase` to update the totals in the application state
2. Have the `InputLayoutController` listen to changes to the totals and update the view
<details>
<summary>Use case</summary</summary>
1. Navigate to https://64f8d7c6e093108e99084a70-nhwccczgbe.chromatic.com/?path=/story/app-externalmessageportprovider--primary
2. Press the `Load random exam` button
3. Confirm the totals view updates
All values are being generated randomly. By pressing the button, the system generates exam data which it passes to the app. Once received, the data goes through the process of validation and update …
> Add use case code to update the values in the totals view

- src/app/responsive-layout-milestone.mdx
Closes #40 
When opening the `Responsive layout milestone` entry in Storybook, the iFrames on the page are sized to large and cover the entire screen. No scrolling is possible because of it.
Size the iFrames to 100% and leverage the max-width and aspect-ration properties to allow the frames to size and fit on both mobile and desktop.
> [Bug] Figma examples not sized for mobile

- .github/workflows/npm-publish.yml
- .gitignore
- cspell.json
- custom-elements-manifest-dist.config.mjs
- custom-elements-manifest.config.mjs
- package-lock.json
- package.json
- rollup.config.mjs
- src/web/index.ts
Closes #43
In order to use the components in a different project, like the [ISNCSCI Web project](https.isncscialgorithm.com/), the ui packages need to be deployed to NPM.
1. Update `rollup.config.mjs` and add the configuration objects needed to build the `app`, `core`, and `web` libraries. The libraries are to be published on the root folder so we can then call `npm link` and `npm publish` from the root. We will publish `esm` and `cjs` (CommonJS) packages. We won't create an `iife` (Immediately Invoked Function Expression) as it does not seem necessary. Since the main purpose of the project is to export custom elements, we assume the developer consuming the library will favor the use of `ESM` and will implement their own exports.
2. Add `files` entries in `package.json` so that the proper …
> isncsci-ui publishing pipeline

- src/web/praxisIsncsciIcon/icons/index.ts
- src/web/praxisIsncsciIcon/icons/regularClose24.ts
- src/web/praxisIsncsciIcon/icons/regularClose32.ts
- src/web/praxisIsncsciIcon/praxisIsncsciIcon.mdx
- src/web/praxisIsncsciIcon/praxisIsncsciIcon.stories.ts
- src/web/praxisIsncsciIcon/praxisIsncsciIcon.ts
Closes #54 
- We need an icon component that can receive a name, theme, and size and render the appropriate SVG icon graphic
- The element needs to be implemented in a way that only the referenced icons end up as part of the code bundle
- The close icon is the first icon we need to support as it is needed for the classification dialog
I crated the `<praxis-isncsci-icon />` which receives the attribute `component` to know what icon to load. Example:
```html
<praxis-isncsci-icon component="regular-close-24"></praxis-isncsci-icon>
```
I created individual custom elements for each icon so that they can be imported when needed, this way only the icons that are being used are added to the bundle.
1. Go to the icons entry of [Storybook](https://64f8d7c6e093108e99084a70-ykwmzqhtpl.chromatic.com/?p …
> [Classification dialog] Close icon

- custom-elements.json
- src/web/praxisIsncsciIcon/icons/index.ts
- src/web/praxisIsncsciIcon/icons/regularClose12.ts
- src/web/praxisIsncsciIcon/icons/regularClose16.ts
- src/web/praxisIsncsciIcon/icons/regularClose20.ts
- src/web/praxisIsncsciIcon/icons/regularClose28.ts
- src/web/praxisIsncsciIcon/icons/regularClose48.ts
- src/web/praxisIsncsciIcon/praxisIsncsciIcon.mdx
- src/web/praxisIsncsciIcon/praxisIsncsciIcon.stories.ts
- src/web/praxisIsncsciIcon/praxisIsncsciIcon.ts
- src/web/praxisIsncsciTotals/praxisIsncsciTotals.stories.ts
Closes #56 
We only generated versions of the close icon for sizes 24 and 32. We need to add the missing supported sizes of 12, 16, 20, 28, and 48.
We also need to add a friendlier way to switch icons in StoryBook.
I've added the extra `svg` files and icon components.
For **StoryBook** I added a _Primary_ story where the visitor can change the theme, icon name, and size using drop downs.
<details>
1. Navigate to the Icon `Primary` story in **StoryBook** `?path=/story/webcomponents-praxisisncsciicon--primary&args=size:48`
2. Using the argument controls at the bottom, cycle through the different icon sizes
3. Confirm that versions of the `close` icon exist for all supported sizes
</details>
> Add all supported icon sizes for `close`

- package-lock.json
- package.json
Related to #62 
I forgot to add the new class exports to the `package.json` files entry so that they are included in the package.
Add the following entries under files:
- "app/providers/cjs/index.js"
- "app/providers/esm/index.js"
- "app/store/cjs/index.js"
- "app/store/esm/index.js"
> Added store and provider exports to package

- rollup.config.mjs
- src/app/providers/externalMessagePort.provider/index.ts
Closes #62 
In order to instantiate an App, we need to pass as parameters the appStore and the providers. This is the way to customize the way the app behaves. The current exported NPM package does not export these items. We need to add them to the Rollup configuration so they get also exported.
const app = new App(appStore, new AppStoreProvider(appStore));
I've added the following paths to the **Rollup** configuration so that their exports are also produced:
- `src/app/providers/index.ts`
- `src/app/providers/externalMessagePort.provider/index.ts`
<details>
1. Run `npm run build`
2. Open the files `app/store/esm/index.js` and `app/providers/esm/index.js` created by the build script
3. Confirm there are exports for `appStore` and the providers in the project …
> Export appStore and all providers along with app package

- assets/css/_classification-grid.css
- assets/css/_classification-total.css
- assets/css/_text-scale.css
- assets/css/design-system.css
- assets/index.html
- src/web/praxisIsncsciClassification/praxisIsncsciClassificationGrid.mdx
- src/web/praxisIsncsciClassification/praxisIsncsciClassificationGrid.stories.ts
- src/web/praxisIsncsciClassification/praxisIsncsciClassificationGrid.ts
- src/web/praxisIsncsciClassification/praxisIsncsciClassificationTotal.mdx
- src/web/praxisIsncsciClassification/praxisIsncsciClassificationTotal.stories.ts
- src/web/praxisIsncsciClassification/praxisIsncsciClassificationTotal.ts
Closes #70 
The classification dialog uses grids to display the classification results.
The grids are used to display the classification results for the motor and sensory scores, as well as the sub-scores.
A grid component that can be used to display the classification results.
We favour composition, so we are using slots to allow the user to customize the heading and the grid.
I believe this approach will prove beneficial when we add internationalization.
<details>
1. Navigate to `?path=/story/webcomponents-classification-grid--primary`
2. Confirm that a 3 column grid is displayed following the specs in figma:
</details>
<details>
1. Navigate to `?path=/story/webcomponents-classification-grid--subscores`
2. Confirm that a 4 column …
> Classification grid

- assets/icons/regular.svg
- src/web/praxisIsncsciIcon/praxisIsncsciIcon.stories.ts
Closes #73
A _hamburger_ icon is required for the app bar menu button
Created the icon, for all supported sizes, in [Figma](https://www.figma.com/file/82mMuohRV0zPWnZbZ5upup/isncsci-app?type=design&node-id=1668-22541&mode=design&t=IxWntaSZoZxBvsRV-0) and imported it to the project.
<details>
1. Go to the **StoryBook** story `?path=/story/webcomponents-praxisisncsciicon--icons`
2. Confirm that the hamburger menu icon is available
> Hamburger menu icon

- assets/css/_dialog-header.css
- assets/css/design-system.css
- src/web/praxisIsncsciDialogHeader/index.ts
- src/web/praxisIsncsciDialogHeader/praxisIsncsciDialogHeader.mdx
- src/web/praxisIsncsciDialogHeader/praxisIsncsciDialogHeader.stories.ts
- src/web/praxisIsncsciDialogHeader/praxisIsncsciDialogHeader.ts
Closes #48 
Dialogs, like the classification dialog, require a header to display the title and close button.
A component that can be used to compose a dialog header.
<details>
1. Navigate to **Storybook** story `?path=/docs/webcomponents-dialog-header--docs`
2. Confirm that the dialog header renders according to the specifications in the [Figma file](https://www.figma.com/file/82mMuohRV0zPWnZbZ5upup/isncsci-app?type=design&node-id=645-35567&mode=design&t=eoncr2pO3k90fplq-0)
</details>
> Dialog header

- assets/css/_classification.css
- assets/css/_tokens.css
- assets/tokens/custom.value.tokens.json
- assets/tokens/tokens.json
- assets/tokens/tokens.value.tokens.json
- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
- src/web/praxisIsncsciAppLayout/index.ts
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.mdx
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.stories.ts
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.ts
- src/web/praxisIsncsciClassification/praxisIsncsciClassification.mdx
- src/web/praxisIsncsciClassification/praxisIsncsciClassification.ts
- style-dictionary.config.json
Closes #45 
- When performing an ISNCSCI exam, we need a dialog to display the classification and totals
- The component needs to use aria tags to ensure the new totals are picked by screen readers
- The dialog must be full screen on mobile devices and anchor at the bottom on larger screens
- The system needs to be able to close the dialog when the raw values change, as the totals do not longer apply for that exam
Mobile:
Desktop:
Favoring composition, we use slots for the different sections. We use a flex layout to position the different sections.
**Slots**
- `app-bar`
- `input-layout`
- `classification`
<details>
1. Navigate to the **Storybook** story `?path=/docs/webcomponents-praxisisncsciapplayout--docs`
2. In the `Actions` panel make sure that …
> Classification dialog

- .github/workflows/npm-publish.yml
Closes #90
The **GitHub** action `npm-publish.yml` which publishes the packages to NPM is failing with the following error message:
[npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.](https://github.com/praxis-isncsci/ui/actions/runs/6794378424/job/18470694687)
Replace the instancess of `npm ci` with `npm install`
> Fix package publishing CI

- package-lock.json
- package.json
- src/app/providers/index.ts
- src/index.ts
Closes #106 
I missed to include the `IsncsciExamProvider` class in the `app/providers` file and is not being included in the exported NPM package. It needs to be there so it can be instantiated when creating a new app object.
Included the class in the index file and increased the package version to `v0.0.15` so it can be published.
> Include IsncsciExamProvider in NPM package and publish as v0.0.15

- assets/css/_cell.css
- assets/css/design-system.css
- custom-elements.json
- src/app/app.stories.ts
- src/app/controllers/inputLayout.controller.ts
- src/app/providers/appStore.provider.ts
- src/app/store/appStore.ts
- src/app/store/reducers.ts
- src/app/webApp.ts
- src/core/boundaries/iAppState.ts
- src/core/boundaries/iIsncsciAppStore.provider.ts
- src/core/useCases/selectPoint.useCase.ts
- src/web/praxisIsncsciCell/praxisIsncsciCell.mdx
- src/web/praxisIsncsciCell/praxisIsncsciCell.stories.ts
- src/web/praxisIsncsciCell/praxisIsncsciCell.ts
- src/web/praxisIsncsciGrid/praxisIsncsciGrid.mdx
- src/web/praxisIsncsciGrid/praxisIsncsciGrid.stories.ts
- src/web/praxisIsncsciGrid/praxisIsncsciGrid.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.ts
Closes #110 
The most basic way to select cells on the ISNCSCI input grid is by clicking with the mouse. The behaviour needs to be implemented.
I don't want the grid component to have to keep track of selection. We have an application state that should track that, that way it can be shared amongst components, like grids and diagram. The input controller will capture the clicks and call the appropriate use case to update the selection. The views will be updated when the states change and will receive the names associated to the cells selected through an attribute (events up, attributes down).
<details>
1. `npm run build`
2. `npm start`
3. Navigate to `http://localhost:44333/`
4. On the grid, click on a cell
5. Confirm that it is highlighted with a purple border …
> Select cell with mouse

- src/core/helpers/index.ts
- src/core/helpers/regularExpressions.spec.ts
- src/core/helpers/regularExpressions.ts
Closes #125 
We need a `sensoryValueRegex` and `motorValueRegex` so we can tell the type of input we are getting and validating before attempting to update the cells.
We also need a `sensoryCellRegex` to return true for  light touch or pin prick valid cell names.
> [Cell input] + Regex for motor and sensory values and sensory cell

- src/app/providers/appStore.provider.ts
- src/app/store/appStore.ts
- src/app/store/reducers.ts
- src/core/boundaries/iAppState.ts
- src/core/boundaries/iIsncsciAppStore.provider.ts
- src/core/useCases/index.ts
- src/core/useCases/setActiveCell.useCase.spec.ts
- src/core/useCases/setCellsValue.useCase.spec.ts
- src/core/useCases/setCellsValue.useCase.ts
Closes #131 
We want updating cell values to fulfill the following use case:
1. Test value to make sure it is valid.
2. Check if there is a single cell selected and `propagateDown` is set to `true` - we only propagate down if there is a single cell selected.
2.2. If the selected cell is a sensory cell and the value is not a motor value, we stop. Nothing gets updated.
2.3. Get the range of cells to update.
2.4. Call `appStoreProvider.setCellsValue` with the range of cells and the value.
3. If there is more than one cell selected or `propagateDown` is ignored:
3.1. Filter out the sensory cells if the value is a motor only value, add all cells to be updated otherwise.
4. If there are no cells to update, we stop. Nothing gets updated.
5. Call `appStoreProvider.setCellsValue` with the cells to …
> [Cell input] Update cell values use case

- src/designSystem/shadows/shadows.mdx
- src/designSystem/shadows/shadows.stories.ts
Closes #135 
There is no **Storybook** story showing how to use the design system shadows.
We added the **Storybook** stories to show the shadows CSS.
1. Navigate to the **Storybook** story: http://localhost:6006/?path=/docs/designsystem-shadows--docs
2. Confirm the documentation for shadows is available
> Add Storybook stories for shadows

- jest.config.ts
- src/app/controllers/inputLayout.controller.ts
- src/app/providers/appStore.provider.ts
- src/app/store/appStore.ts
- src/app/store/reducers.ts
- src/core/boundaries/iAppState.ts
- src/core/boundaries/iIsncsciAppStore.provider.ts
- src/core/domain/binaryObservation.ts
- src/core/domain/index.ts
- src/core/useCases/setActiveCell.useCase.spec.ts
- src/core/useCases/setCellsValue.useCase.spec.ts
- src/core/useCases/setVacDap.spec.ts
- src/core/useCases/setVacDap.useCase.ts
- src/testHelpers/appStoreProviderMocks.ts
- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.stories.ts
Closes #143 
The `VAC` and `DAP` drop downs need to be connected to the application state so that when they change, their values are set in the state.
I added listeners for the `change` event for `VAC` and `DAP`. They call the `setVacDap.useCase` which updates the state. When the state changes, the **input layout controller** updates the components.
> Update VAC and DAP use cases

- assets/css/_extra-inputs.css
- assets/css/_tokens.css
- assets/tokens/tokens.json
- assets/tokens/tokens.value.tokens.json
- src/web/index.ts
- src/web/praxisIsncsciExtraInputs/index.ts
- src/web/praxisIsncsciExtraInputs/praxisIsncsciExtraInputs.mdx
- src/web/praxisIsncsciExtraInputs/praxisIsncsciExtraInputs.stories.ts
- src/web/praxisIsncsciExtraInputs/praxisIsncsciExtraInputs.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.ts
Closes #146 
[Figma](https://www.figma.com/file/82mMuohRV0zPWnZbZ5upup/isncsci-app?type=design&node-id=578-22681&mode=design&t=7c6Ut5KoGnrFD44a-0)
Implement the lowest non-key muscles and comments section on the UI as specified in Figma.
I approached the component using composition. The component has all the **CSS** needed to provide the proper layout and spacing for mobile and larger breakpoints. Slots are used to allow the user to provide the proper **HTML** elements for the labels and inputs, giving flexibility to the developers using the component and making things easy when adding internationalization.
<details>
1. Navigate to the [extra inputs story](https://64f8d7c6e093108e99084a70-rcycvdzpuo.chromatic.com/?path=/docs/webcomponents-praxisisncsciextrainpu …
> Lowest non-key muscles and comments UI

- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.stories.ts
Fixes #150 
The extra inputs were removed from the bottom of the `PraxisIsncsciInputLayout` **Storybook** story.
Add the markup for the slots to the story and make the `container-type` **CSS** property on the story's `#root-inner` element so that the container queries get applied.
> [Bug] Input layout story is missing the extra inputs

- assets/css/_app-bar.css
- assets/index.html
- src/app/app.stories.ts
- src/app/controllers/inputLayout.controller.ts
- src/app/webApp.ts
- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.stories.ts
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.ts
Closes #157 
[Figma](https://www.figma.com/file/82mMuohRV0zPWnZbZ5upup/isncsci-app?type=design&node-id=699-51085&mode=design&t=14pHBbRqPfO4aouN-0)
The contents of the classification dialog are not visible, only the heading. Layout issues seem to have been introduced when we added the input buttons. Having them as part of the input layout was a bad decision, as they are more of global components that need to be repositioned in the layout. The area with the grids is not properly resizing and showing a scroll bar, but pushing the classification panel out of sight.
1. I moved the **input buttons** out of the **input layout** and make them part of the application layout. There, we can use the `order` property of the `flex` layout to easily reposition the component between medium and large …
> [Bug] Classification dialog is not showing

- custom-elements.json
- src/app/app.stories.ts
- src/app/webApp.ts
- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.stories.ts
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.ts
Closes #160 
We need to add `readonly` attributes to the `praxis-isncsci-web-app` and the `praxis-isncsci-app-layout` components.
**Web App**
- Sets the classification panel as `static` at the bottom of the interface
**App layout**
- Makes input controls `readonly` or `disabled` if they are select boxes
- Hides the input buttons
---
<details>
1. Navigate to the `praxis-isncsci-app-layout` [**Storybook** story](https://64f8d7c6e093108e99084a70-pfcolsmzzw.chromatic.com/?path=/story/webcomponents-praxisisncsciapplayout--primary)
2. Set the `readonly` control to `true`
3. Confirm that:
1. The input buttons are removed from the interface
2. The VAC, DAP, and select boxes for lowest non-key muscles with motor function are disabled
3. The comments text are gets …
> Add readonly attributes to web components

- package-lock.json
- src/app/providers/appStore.provider.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.mdx
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.stories.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.ts
- src/app/store/appStore.ts
- src/app/store/reducers.ts
- src/app/webApp.ts
- src/core/boundaries/iAppState.ts
- src/core/boundaries/iIsncsciAppStore.provider.ts
- src/core/useCases/index.ts
- src/core/useCases/loadExternalExamData.useCase.ts
- src/core/useCases/setReadonly.spec.ts
- src/core/useCases/setReadonly.useCase.ts
- src/testHelpers/appStoreProviderMocks.ts
Add a `readonly` flag to the application state to be flipped by a request coming from `ExternalMessagePortProvider`
When passing exam data, the a `readonly` flag can also be provided which would affect the application state and update the interfaces.
- Added a use case to set the `readonly` state flag
- Allow the **external message provider** to pass a `readonly` value along with exam data
- Added a `setReadonly` handler to the **external message provider** to set the `readonly` value without requiring passing exam data
- Update the interface based on the chantes to the state
<details>
1. Navigate to the [ExternalMessagePortProvider primary Storybook story]()
2. Press the button `Load random exam as readonly`
3. Confirm that:
- Exam data passed by the …
> Allow the `ExternalMessagePortProvider` to activate the `readonly` application state

- src/app/providers/appStore.provider.ts
- src/app/store/reducers.ts
- src/core/boundaries/iIsncsciAppStore.provider.ts
- src/core/domain/cell.ts
- src/core/helpers/examData.helper.ts
- src/core/helpers/regularExpressions.spec.ts
- src/core/helpers/regularExpressions.ts
- src/core/useCases/setActiveCell.useCase.spec.ts
- src/core/useCases/setCellsValue.useCase.spec.ts
- src/core/useCases/setCellsValue.useCase.ts
Closes #167 
I want the details around _reason for impairment not due to SCI_ to be reset when setting a value. I want to create a separate use case to set `consider normal`, `reason`, `reason specify.
It is a bit unintuitive how the controls were finalized. We were not allowed to specify wether a value should be considered normal or not normal when initially setting it. This is a business decision I was not able to fight back. As a result, when initially setting the flag, the cell needs to be marked as having an input error. I think all this can be handled in `setCellsValueUseCase`.
- Added `error: string | undefined` to the `Cell` interface
- Updated the providers to receive the error, reason for impairment not due to SCI, and comments when setting a value
- Updated the …
> [Cell input wire star values] Update star values when setting initial value

- src/core/useCases/index.ts
- src/core/useCases/setCellsValue.useCase.ts
- src/core/useCases/setStarDetails.useCase.spec.ts
- src/core/useCases/setStarDetails.useCase.ts
Closes #169 
Add a use case to handle setting values associated to cells flagged as having impairment not due to SCI for the following items:
- Consider normal or not normal
- Reason
- Reason details
**Cases**
- When multiple cells are selected, do not update if the values are not identical, throw an error
- If down propagation is on, update all cells below that have the same initial value and stop until you find one that does not match
Added a use case to handle changes to the values associated to impairment not due to SCI.
- Ensure unit tests cover the different aspects of the use case
- Ensure use case code makes sense
> [Cell input wire star values] Update elegible cells after setting a star input value

- assets/css/_cell.css
- assets/css/_tokens.css
- assets/tokens/primitives.value.tokens.json
- assets/tokens/tokens.json
- assets/tokens/tokens.value.tokens.json
- src/web/praxisIsncsciCell/praxisIsncsciCell.mdx
- src/web/praxisIsncsciCell/praxisIsncsciCell.stories.ts
- src/web/praxisIsncsciCell/praxisIsncsciCell.ts
Related to #170 
When using the `* star` flag, the consider normal field is not set by default. The interface needs to show which cells are missing the extra information. The cell needs styling to reflect this state.
Added the `error` state to the cell. The cell now takes an `error` attribute. When marked with this attribute, the foreground and background color change and a `!` icon is used to call for the user's attention.
<details>
1. Navigate to the [cell's error story](https://64f8d7c6e093108e99084a70-rjjqzpxonc.chromatic.com/?path=/story/webcomponents-input-cell--error)
2. Confirm that the error styling is applied when the `error` attribute is present
</details>
> Add error styles to cell

- package-lock.json
- package.json
Closes #177 
We get an exception when building `isncsci\web` on a project importing the library via **NPM**.
Add `core/helpers/cjs/index.js` and `core/helpers/esm/index.js` to the package's files.
> Added core/helpers to package

- package-lock.json
- package.json
- rollup.config.mjs
- src/app/controllers/index.ts
- src/app/webApp.ts
The modules under the `app/controllers` folder are not being exported therefore cannot be used outside `webApp`
- Add `index.ts` to the `app/controllers` folder
- Add the new index file to the list of files to be included in the **Rollup** bundle
> Add controllers to package

- assets/index.html
Closes #190 
On **Chrome** , when setting the height to `100vh`, the address bar height is not deducted from the height. The input buttons are getting cut at the bottom on the phone.
Here is a good description of the problem: https://stackoverflow.com/questions/52848856/100vh-height-when-address-bar-is-shown-chrome-mobile
Use `100dvh` instead
<details>
1. On **Chrome** on your **Android** phone, navigate to the [test site](https://brave-meadow-05543dc10-191.centralus.4.azurestaticapps.net/)
2. Confirm that the app is the right height and the input buttons are not getting cut off
</details>
> [bug] Input buttons getting cut on pixel phone

- assets/css/_classification.css
- assets/css/_tokens.css
- assets/tokens/tokens.json
- assets/tokens/tokens.value.tokens.json
- src/web/praxisIsncsciClassification/praxisIsncsciClassification.ts
Closes #111 
The **CSS** `blur` filter does not work in safari. Instead of getting an acrylic effect, we get an empty background for the classification dialog.
- I added `-webkit-backdrop-filter: var(--backdrop-filter, blur(1.5rem));`, in addition to the line with just `backdrop-filter`
<details>
1. In **Safari**, navigate to the [App **Storybook** story](https://64f8d7c6e093108e99084a70-zssmokaurz.chromatic.com/?path=/story/app-app--primary)
2. Set the viewport size to `Large mobile`
3. Press the `Calculate` button
4. Confirm that the Classification dialog's background resembles an acrylic surface and blurs the contents behind it
</details>
> [Bug] Acrylic effect not working in Safari

- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.stories.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.ts
- src/core/useCases/loadExternalExamData.useCase.spec.ts
There is an issue in `src/app/providers/externalMessagePort.provider/externalMessagePort.provider.ts` where the values from the incoming data are being incorrectly assigned when passing them to the event handlers.
- Fixed the issue with the incoming data
- Added a button to test incoming incomplete exam data
- Added unit test
<details>
1. Navigate to the [external message port provider **Storybook** story](https://64f8d7c6e093108e99084a70-toznrbndwf.chromatic.com/?path=/story/app-app--primary)
2. Press the `Load random incomplete exam` button
3. Confirm that data is being loaded
</details>
> Fix issue with incoming data

- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
The **light touch total** is blank after performing a calculation
We missed to update `src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts` when whe renamed `touchTotal` to `lightTouchTotal` #201 
We just had to update the string in the file.
<details>
1. Navigate to the [App **Storybook** story]()
2. Complete an exam
3. Press the `Calculate` button
4. Confirm that all totals are being populated
</details>
> [bug] Missing calculated total

- src/app/controllers/keyPointsDiagram.controller.ts
- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
- src/web/praxisIsncsciInput/praxisIsncsciInput.mdx
- src/web/praxisIsncsciInput/praxisIsncsciInput.stories.ts
- src/web/praxisIsncsciInput/praxisIsncsciInput.ts
Closes #209 
External systems that will be embedding the ISNCSCI Calculator need `UNK` as an option. This value is used to indicate a field has been left blank on purpose. Very common for systems collecting short versions of the form where only motor values are entered.
- Add a `UNK` button that is hidden by default
- Add `UNK` as an input option
- Update key points diagram when `UNK` is present
<details>
1. Navigate to the [PraxisIsncsciInput **Storybook** Sensory story](https://64f8d7c6e093108e99084a70-frgcdryoln.chromatic.com/?path=/story/webcomponents-isncsci-input--sensory)
2. In the controls section, set `showUnknown` to `true`
4. Confirm there is a new `UNK` button between `5` and `NT`
> [connect] Add UNK as input option

- src/app/app.stories.ts
- src/core/domain/isncsciLevels.ts
- src/core/helpers/examData.helper.ts
- src/core/helpers/regularExpressions.spec.ts
- src/core/helpers/regularExpressions.ts
- src/core/useCases/calculate.useCase.ts
- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
Closes #211 
Third party applications that embed this application, like **Praxis Connect**, allow the collection of `UNK` as value. This value is used in cases where cells are left empty on purpose in a database. This is a very common behaviour for systems that allow the collection of short version ISNCSCI where only motor values are collected.
- We are allowing the collection of unknown values. They need to be treated as NT when classifying an exam.
- We allow passing a flag to the **app layout template** to show or hide the `UNK` in the inputs.
<details>
1. Navigate to the [App primary Storybook story with the `show unknown` flag turned set to `true`](https://64f8d7c6e093108e99084a70-rzygihasdt.chromatic.com/?path=/story/app-app--primary&args=showUnknown:!tru …
> [connect] Allow the classification to take place when UNK is present

- package-lock.json
- package.json
- src/core/domain/examData.ts
- src/core/helpers/examData.helper.ts
- src/core/useCases/calculate.useCase.ts
Closes #214 
As part of the payload being passed to a containing system via the external message provider we need to pass a boolean to indicate if a form is complete.
A complete form is a form with all values, including VAC and DAP, as well as classfication.
- Added the property `isComplete` to the `examData` object
- Set the flag to `true` when a form is complete and a classification has been produced
<details>
1. Navigate to [external message provider **Storybook** story]()
2. Press the **Load random exam** button
3. Press the **Calculate** button
4. Open the developer panel
5. Confirm that the classified exam data has been sent out by looking at the data on the console
6. Confirm that the `isComplete` flag is set to true
</details>
> [connect] Report the form completion state on change or classification

- package-lock.json
- package.json
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.spec.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.stories.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.ts
- src/app/webApp.ts
- src/core/useCases/loadExternalExamData.useCase.spec.ts
- src/core/useCases/loadExternalExamData.useCase.ts
Closes #223 
We need to let external applications decide what display style to use.
We expose the classification style property so they can change it using the external port.
You can test the different styling options in the [Storybook story](https://64f8d7c6e093108e99084a70-gjzqmtapam.chromatic.com/?path=/story/app-externalmessageportprovider--primary)
> [Connect] Make classification style optional

- package-lock.json
- package.json
- src/core/useCases/setStarDetails.useCase.spec.ts
- src/core/useCases/setStarDetails.useCase.ts
Closes #224 
The application runs into an infinite loop when:
1. We select `C5 motor`
2. We press the `1*` input button, setting all right motor values to `1*`
3. We select `consider normal` from the star details inputs
4. The `propagateDown` flag is set to true
The part of the code that determines the range of cells to be modified is not properly increasing its counter when it finds a row with no motor cell.
Make sure that the counter in the loop gets incremented on every iteration.
<details>
1. Navigate to the [dev page](https://brave-meadow-05543dc10-231.centralus.4.azurestaticapps.net)https://brave-meadow-05543dc10-231.centralus.4.azurestaticapps.net/
2. Select `C5 Motor`
3. Press the `1*` input button
4. From the star values inputs that appeared in the …
> Praxis Connect ISNCSCI control - page freezes when using * as input

- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.mdx
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.spec.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.stories.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.ts
- src/app/webApp.ts
Closes #229
**Praxis Connect** wants control to trigger the classification on their end.
I've added a `CLASSIFY` action to the **external message port provider** so that the classification process can be triggered by the importing system.
<details>
1. Navigate to the [external message provider **Storybook** story](https://64f8d7c6e093108e99084a70-rcpbswrfmy.chromatic.com/?path=/story/app-externalmessageportprovider--primary)
2. Press the **Load random exam** button
3. Confirm that the form gets populated
4. Press the **Classify** button
5. Confirm that the classification panel opens with the results of the calculation
</details>
> [connect] Expose the calculation function to Praxis Connect

- src/core/domain/binaryObservation.ts
- src/core/helpers/examData.helper.ts
- src/core/helpers/index.ts
- src/core/useCases/calculate.useCase.spec.ts
Closes #226 
`UNK` is missing as a valid **VAC** and **DAP** value making the exams not pass validation during calculation.
Added `UNK` to the enumerations in `binaryObservation.ts` making it a valid input. They get converted from `UNK` to `NT` during the calculation process.
<details>
1. Navigate to the [dev build associated to this issue](https://brave-meadow-05543dc10-234.centralus.4.azurestaticapps.net)
2. Enter all normal values for motor and sensory
3. Select `UNK` for **VAC** and **DAP**
4. Press calculate
5. Confirm that the calculation is successful
</details>
> Isncsci data input loss when saving partially completed isncsci with missing VAC and DAP or VAC and DAP=UNK

- package-lock.json
- package.json
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.ts
Closes #227 
In certain screen breakpoints, the key points diagram is overlapping with the grid and bottom input elements.
- Do not use `position: fixed` on the diagram is the screen height is less than `1224px`. This way there will be no overlap with the bottom input elements
- Show the diagram, but at 80% size, when the screen is at least `850px` wide
- Set the diagram size to 100% when the screen size is at least `930px` wide
> [227] Overlapping human body image and input data

- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.ts
Closes https://github.com/praxis-isncsci/ui/issues/239
Thank you for letting me contribute to this project.
Diagram is not centered
added ``grid-gap of 3rem i.e var(--space-12)``
> [239] Praxis Connect ISNCSCI control - Body diagram is not centred
