- README.md
Closes #1
> As a **developer**, when working on the ISNCSCI PWA, I want to work inside a Docker Development Environment so I can guarantee I am developing in the same conditions as my colleagues.
Created and documented a `devcontainer` configuration that supports working with node and Typescript and that can allow us to work with Ionic in the future.
1. Follow the instructions in file  `README.md` under `## Develop using VS Code Development Environment`
2. Confirm it is possible to open an development environment in VS Code with node installed
> Setup Docker for Ionic development

- .prettierrc
- .vscode/settings.json
- src/designSystem/color/colorGroup.ts
Closes #26
As the codebase grows, it is getting harder to keep the code formatting consistent. We need to apply the following automated rules:
1. Format on save
2. Enforce the use of trailing commas
3. Enforce a tab width of 2 spaces
4. Enforce semicolons at the end of statements
5. Enforce the use of single quotes
6. Set bracket spacing to 0 (space between bracket or curly brackets and code)
```json
"trailingComma": "es5",
"tabWidth": 2,
"semi": true,
"singleQuote": true,
"bracketSpacing": false
```
<details>
<summary>Test Case</summary>
1. Alter a TypeScript file formatting
7. Save the file
8. Confirm it gets auto-formatted
</details>
> Set code formatting rules

- assets/css/design-system.css
- src/designSystem/color/color.stories.ts
- src/web/praxisIsncsciGrid/praxisIsncsciGrid.stories.ts
- src/web/praxisIsncsciGrid/praxisIsncsciGrid.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.stories.ts
There are issues with naming and formatting in some stories.
Do a little cleanup of the code before more stories are affected
> [bug] Stories referencing the design system CSS file have a purple background

- .prettierrc
- .storybook/preview.ts
- custom-elements-manifest.config.mjs
- custom-elements.json
- package-lock.json
- package.json
- src/designSystem/color/color.mdx
- src/designSystem/color/colorGroup.ts
- src/designSystem/color/colorSwatch.ts
- src/web/praxisIsncsciCell/praxisIsncsciCell.ts
- src/web/praxisIsncsciGrid/praxisIsncsciGrid.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.ts
- src/web/praxisIsncsciTotals/index.ts
- src/web/praxisIsncsciTotals/praxisIsncsciTotals.mdx
- src/web/praxisIsncsciTotals/praxisIsncsciTotals.stories.ts
- src/web/praxisIsncsciTotals/praxisIsncsciTotals.ts
Closes #16 
In order to begin the **Praxis Connect** integration, we need a simple totals component to allow us to see the data coming from the database. It does not need to be styled, it needs to reflect the incoming data.
1. Add simple totals view to show the data in the state
2. Add `custom-elements.json` manifest file to allow **StoryBook** to detect the attributes from our web components
3. Update **StoryBook** so it can consume the `custom-elements.json` manifest
> Simple totals view to show raw data

- src/app/responsive-layout-milestone.mdx
We want the first pass to the responsive layouts to be documented in **Storybook** as a milestone.
I've added a new story documenting all design decision around the new interface proposal.
Navigate to the story at `?path=/docs/app-milestones-1-responsive-layout-milestone--docs` and review the content, spelling, and grammar.
> Documentation for responsive layout milestone

- package-lock.json
- package.json
Related to #62
Needed for publishing **NPM** packages
> Increased version number to 0.0.2

- package-lock.json
- package.json
- rollup.config.mjs
Closes #66 
Not all files under `app/` are being added to the final package on **NPM**.
In `package.config`, under `files` replace:
```json
"app/cjs/index.js",
"app/esm/index.js",
"app/providers/cjs/index.js",
"app/providers/esm/index.js",
"app/store/cjs/index.js",
"app/store/esm/index.js",
```
with: `"app/*/**/index.js",`
Confirm all app files are part of the [NPM package v0.0.8](https://www.npmjs.com/package/isncsci-ui/v/0.0.8?activeTab=code)
> [bug] App package does not include all files

- assets/css/_classification.css
- assets/css/_tokens.css
- assets/tokens/custom.value.tokens.json
- assets/tokens/tokens.json
- assets/tokens/tokens.value.tokens.json
- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
- src/web/praxisIsncsciAppLayout/index.ts
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.mdx
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.stories.ts
- src/web/praxisIsncsciAppLayout/praxisIsncsciAppLayout.ts
- src/web/praxisIsncsciClassification/praxisIsncsciClassification.mdx
- src/web/praxisIsncsciClassification/praxisIsncsciClassification.ts
- style-dictionary.config.json
Closes #45 
- When performing an ISNCSCI exam, we need a dialog to display the classification and totals
- The component needs to use aria tags to ensure the new totals are picked by screen readers
- The dialog must be full screen on mobile devices and anchor at the bottom on larger screens
- The system needs to be able to close the dialog when the raw values change, as the totals do not longer apply for that exam
Mobile:
Desktop:
> Classification dialog

- package-lock.json
- package.json
We need this to publish the NPM package and test integration with Praxis Connect
> Increas version to v0.0.9

- .gitignore
- package-lock.json
- package.json
- rollup.config.mjs
Our WebComponent packages work well but we have not been publishing the CSS along with them. This is making it hard to get the full look and feel we are creating in the public website.
I've added the CSS files to the bundle. The receiving application can decide how to bundle them.
> Bundle and package CSS

- package-lock.json
- package.json
Closes #102 
We need to increase the version number to publish the package. The new version is needed to test the saving mechanism in **Praxis Connect**
Increase to v0.0.14
> Increase to v0.0.14

- package-lock.json
- package.json
- rollup.config.mjs
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.stories.ts
- src/app/webApp.ts
- src/testHelpers/examDataHelper.ts
- tsconfig.json
Closes #108 
The cells in the input grid are not being generated. The grids show blank.
The **Storybook** story with the function to generate random exam data was calling `SensoryLevels.splice` clearing that constant. `slice` should be used instead.
I was reusing that function as I am not sure if we will need it outside the story once the current **Praxis Connect** testing concludes, but I decided to pull it into a helper anyways as making it public is also breaking the tests in **Chromatic**.
Upgrade the library in the public website and confirm the app renders properly again.
> [Bug] Grid cells are not populating

- assets/css/_isncsci-input.css
- assets/css/design-system.css
- src/web/index.ts
- src/web/praxisIsncsciInput/index.ts
- src/web/praxisIsncsciInput/praxisIsncsciInput.mdx
- src/web/praxisIsncsciInput/praxisIsncsciInput.stories.ts
- src/web/praxisIsncsciInput/praxisIsncsciInput.ts
Closes #120 
Implement the button design from [Figma](https://www.figma.com/file/82mMuohRV0zPWnZbZ5upup/isncsci-app?type=design&node-id=132-15105&mode=design&t=zsIKWtIiSUhGIW7y-0) which supports entry for values with `*`.
We use a flex layout to easily switch from row, when on large screens, to column, when on small screens. For the button section we use a grid layout to easily align the buttons.
We use real buttons so we get all the accessibility goodies.
- This PR only includes the active state for the buttons. Other states, like disabled and hover will be done in #122.
- Testing should be focus in the look and feel of the buttons and ensuring we created the necessary CSS variables for the components.
- Testing can be done using the **Storybook** story …
> Button element that supports `*`

- README.md
Closes #133 
We need instructions in the `README` file to help testers setup a codespace for reviewing.
Add the following instructions:
1. Log into GitHub
2. Navigate to the PR
3. At the top of the PR, click on the branch associated to it
4. Open the branch using a GitHub codespace
5. Wait for the codespace to be created
6. Open a terminal
7. Run `npm install` to install all dependencies
8. Run `npm run storybook` to start the storybook server
9. Open the storybook server in a browser
10. Run `npm run build` to build the project
11. Run `npm run start` to start the development server
12. Open the development server in a browser
> Add instructions for PR review

- assets/css/_isncsci-input.css
- assets/css/_tokens.css
- assets/tokens/custom.value.tokens.json
- assets/tokens/tokens.json
- assets/tokens/tokens.value.tokens.json
- src/web/praxisIsncsciInput/praxisIsncsciInput.mdx
- src/web/praxisIsncsciInput/praxisIsncsciInput.stories.ts
- src/web/praxisIsncsciInput/praxisIsncsciInput.ts
Closes #122 
[Figma](https://www.figma.com/file/82mMuohRV0zPWnZbZ5upup/isncsci-app?type=design&node-id=132-15105&mode=design&t=3asV2VLz6eLNk9Ae-0)
We need button states for the top input buttons so that the users can get visual and tactile feedback when interacting with them.
I updated the designs in Figma and added button states for:
- Hover - Makes a transition from white background to light lilac. It also adds a drop shadow to the button group.
- Selected - Background changes to bright lilac and font color to white.
- Pressed - Reduces the font size and makes the background a darker version of lilac.
- Disabled - Adds a light, grey background to the button.
I added design tokens to support the new styles.
I also added the following attributes to the input component:
- `selected-value` …
> Implement states for ISNCSCI input button (e.g. disabled, hover, selected)

- src/app/controllers/inputLayout.controller.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.ts
Closes #138 
Enabling and disabling of input buttons needs to be linked to the selected cell. The listeners and code to handle the UI login need to be added.
`InputLayoutController` handles the UI update for the input controls as part of the `SET_ACTIVE_CELL` and `SET_CELL_VALUE` app state event handling.
<details>
1. Navigate to **Storybook** story `?path=/story/app-app--primary`
2. Confirm no cell is selected and all input buttons are disabled
</details>
---
<details>
1. Navigate to **Storybook** story `?path=/story/app-app--primary`
2. Select a motor cell
3. Confirm all input buttons are enabled
</details>
---
<details>
1. Navigate to **Storybook** story `?path=/story/app-app--primary`
2. Select a …
> Set selected value on input button and disable motor buttons when sensory cell is active

- src/app/controllers/inputLayout.controller.ts
- src/app/providers/appStore.provider.ts
- src/app/store/appStore.ts
- src/app/store/reducers.ts
- src/core/boundaries/iAppState.ts
- src/core/boundaries/iIsncsciAppStore.provider.ts
- src/core/useCases/setExtraInputs.useCase.spec.ts
- src/core/useCases/setExtraInputs.useCase.ts
- src/core/useCases/setVacDap.spec.ts
- src/core/useCases/setVacDap.useCase.ts
- src/testHelpers/appStoreProviderMocks.ts
- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
- src/web/praxisIsncsciInputLayout/praxisIsncsciInputLayout.ts
Closes #147 
The recently added input controls for right and left lower non-key muscles with motor function and comments need to be wired to the application state cycle.
- Add the **core** use case and state provider methods to collect the data and persist it in the application state
- Add the methods in the application codes to implement the provider methods from core interfaces and use the use case
> Lowest non-key muscles and comments interaction

- package.json
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.ts
- src/app/webApp.ts
- src/core/domain/examData.ts
- src/core/helpers/examData.helper.spec.ts
- src/core/helpers/examData.helper.ts
- src/core/useCases/calculate.useCase.ts
- src/core/useCases/initializeApp.useCase.ts
- src/core/useCases/loadExternalExamData.useCase.ts
- src/core/useCases/setActiveCell.useCase.spec.ts
- src/core/useCases/setCellsValue.useCase.spec.ts
Closes #21 
`calculate.useCase` generates a random exam and then calculates the classification. It should use the values entered by the user instead.
Remove random exam calculation, and use input values for VAC, DAP, and lowest non-key muscles with motor function when producing classification.
<details>
1. Navigate to [App Storybook story](https://64f8d7c6e093108e99084a70-rnwjluteuw.chromatic.com/?path=/story/app-app--primary)
2. Complete an exam, including values for **VAC** and **DAP**
3. Press the calculate button
4. Confirm that the exam values do not get overwritten and the classification is calculated
</details>
> 21 calculate

- src/app/controllers/inputLayout.controller.ts
- src/app/providers/appStore.provider.ts
- src/app/store/reducers.ts
- src/core/boundaries/iIsncsciAppStore.provider.ts
- src/core/helpers/cellHelper.spec.ts
- src/core/helpers/cellHelper.ts
- src/core/helpers/index.ts
- src/core/useCases/setCellsValue.useCase.spec.ts
- src/core/useCases/setCellsValue.useCase.ts
- src/core/useCases/setStarDetails.useCase.spec.ts
- src/core/useCases/setStarDetails.useCase.ts
- src/web/praxisIsncsciInput/praxisIsncsciInput.mdx
Closes #170 
When changing the values of the input controls for the extra star value inputs, the application state and UI needs to be updated.
- Added the `setStarDetails.useCase` to handle the changes to the input controls
- Updated UI
> [Cell input wire star values] Refresh the interface

- .gitignore
- package-lock.json
- package.json
- rollup.config.mjs
We want to distribute our icons with the package and they are not currently being included.
- Copy them to the root folder during build
- Add the icons folder to the files list in `package.json`
> Add icons to **NPM** package

- .gitignore
- package-lock.json
- package.json
- rollup.config.mjs
- src/core/boundaries/iAppState.ts
- src/core/domain/examData.ts
- src/core/helpers/examData.helper.ts
When using the library in an **Ionic** project, the system requested typings.
- To keep things clean and be able to generate the typings, we are packaging all of our exported modules into a `dist` folder
- Inside `dist` we have the subfolders `esm` and `cjs`
- I have updated the `rollup.config,mjs` file to create the typings for the project
> Generate typings

- src/index.ts
Closes #188 
1. Open the [development site](https://brave-meadow-05543dc10.4.azurestaticapps.net/)
The key points diagram is missing
Add `praxisIsncsciKeyPointsDiagram` to application's index file.
<details>
<summary>Test Case</summary>
1. Open the [development site]()
2. Confirm the diagram loads
</details>
> [bug] Key point diagram not loading on dev site

- assets/css/_app-bar.css
- assets/css/_extra-inputs.css
- assets/css/_input-layout.css
- assets/css/_isncsci-input.css
- assets/css/_tokens.css
- assets/css/design-system.css
- assets/tokens/custom.value.tokens.json
- assets/tokens/tokens.json
- assets/tokens/tokens.value.tokens.json
- src/app/webApp.ts
- src/web/praxisIsncsciAppBar/praxisIsncsciAppBar.mdx
- src/web/praxisIsncsciAppBar/praxisIsncsciAppBar.ts
- src/web/praxisIsncsciClassification/praxisIsncsciClassification.mdx
- src/web/praxisIsncsciExtraInputs/praxisIsncsciExtraInputs.mdx
- src/web/praxisIsncsciExtraInputs/praxisIsncsciExtraInputs.ts
- src/web/praxisIsncsciInput/praxisIsncsciInput.mdx
- src/web/praxisIsncsciInput/praxisIsncsciInput.ts
Closes #192 
The following elements need updating:
> Margins, paddings, and max width

- package-lock.json
- package.json
We are increasing the version so we can publish the latest updates.
> Increase version to `v1.0.0`

- src/app/controllers/inputLayout.controller.ts
- src/app/providers/appStore.provider.ts
- src/app/store/appStore.ts
- src/app/store/reducers.ts
- src/app/webApp.ts
- src/core/boundaries/iAppState.ts
- src/core/boundaries/iIsncsciAppStore.provider.ts
- src/core/domain/examData.ts
- src/core/helpers/examData.helper.ts
- src/core/useCases/calculate.useCase.spec.ts
- src/core/useCases/calculate.useCase.ts
- src/core/useCases/setCellsValue.useCase.spec.ts
- src/core/useCases/setCellsValue.useCase.ts
- src/core/useCases/setExtraInputs.useCase.spec.ts
- src/core/useCases/setExtraInputs.useCase.ts
- src/core/useCases/setStarDetails.useCase.spec.ts
- src/core/useCases/setStarDetails.useCase.ts
- src/core/useCases/setVacDap.spec.ts
- src/core/useCases/setVacDap.useCase.ts
- src/testHelpers/appStoreProviderMocks.ts
- src/testHelpers/examDataHelper.ts
Closes #228 
Users like to be notified when a value is missing and they are attempting to perform a calculation
- Collect missing values and errors identified during calculation
- Add them to the data passed to external listeners
- Show an alert with the error
<details>
1. Navigate to the [**Storybook** External Message Port Provider story](https://64f8d7c6e093108e99084a70-zewvomuhdt.chromatic.com/?path=/story/app-externalmessageportprovider--primary)
2. Press the calculate button
3. Confirm that an alert, with a list of missing values, is presented
4. Open the console in the developer tools section
5. Confirm that the exam data was passed to the external listeners and that the list of missing values is included
</details>
> [228] Expect to get the message for required missing fields while clicking the calculate button.

- package-lock.json
- package.json
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.mdx
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.spec.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.stories.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.ts
- src/app/webApp.ts
- src/core/useCases/clearExam.useCase.ts
- src/core/useCases/index.ts
- src/web/praxisIsncsciAppBar/praxisIsncsciAppBar.stories.ts
- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
Closes #243
We need an action to clear the form. The action needs to be able to be triggered via a button in the main controls and by external systems embedding the component.
> Add clear form functionality and expose to embedding api

- package-lock.json
- package.json
- src/app/controllers/inputLayout.controller.ts
- src/app/providers/externalMessagePort.provider/externalMessagePort.provider.stories.ts
- src/core/useCases/loadExternalExamData.useCase.ts
- src/testHelpers/examDataHelper.ts
> [Bug] Consider normal/not normal dropdown is not updating correctly

- package.json
- src/app/webApp.ts
1. close classification panel when loading external data
2. dont preform classify and shown the panel when there is error in the input
> version 1.0.8

- src/web/praxisIsncsciAppLayout/appLayoutTemplate.ts
- src/web/praxisIsncsciClassification/praxisIsncsciClassification.stories.ts
- src/web/praxisIsncsciClassification/praxisIsncsciClassification.ts
- src/web/praxisIsncsciInput/praxisIsncsciInput.ts
Updated: 1. dynamic label change for motor and sensory impairment; 2. added a separate slot for injury Complete or Incomplete
> 31708 motor sensory impairment
